version: '2'
services:
    eshop-app:
        image: eshop
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eshop-mysql:3306/eshop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=eshop-elasticsearch:9300
        ports:
            - 8080:8080
    eshop-mysql:
        extends:
            file: mysql.yml
            service: eshop-mysql
    eshop-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: eshop-elasticsearch
